# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1001)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(1710, 30, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(1730, 870, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.SerialLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SerialLineEdit.setGeometry(QtCore.QRect(30, 190, 391, 51))
        self.SerialLineEdit.setText("")
        self.SerialLineEdit.setObjectName("SerialLineEdit")
        self.TestButton = QtWidgets.QPushButton(self.centralwidget)
        self.TestButton.setGeometry(QtCore.QRect(440, 190, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TestButton.setFont(font)
        self.TestButton.setObjectName("TestButton")
        self.ResultsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.ResultsTable.setGeometry(QtCore.QRect(30, 270, 791, 311))
        self.ResultsTable.setObjectName("ResultsTable")
        self.ResultsTable.setColumnCount(0)
        self.ResultsTable.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton.setText(_translate("MainWindow", "START"))
        self.StopButton.setText(_translate("MainWindow", "STOP"))
        self.TestButton.setText(_translate("MainWindow", "TEST"))
